ALTER TRIGGER TG_NOTA_MAXIMA
ON MATRICULA
FOR INSERT
AS 
BEGIN
	DECLARE
		@RA_ALUNO VARCHAR(20),
		@NOTA_1 SMALLINT,
		@NOTA_2 SMALLINT

		SELECT @RA_ALUNO = RA_ALUNO FROM INSERTED
		SELECT @NOTA_1 = NOTA_1 FROM INSERTED
		SELECT @NOTA_2 = NOTA_2 FROM INSERTED

		IF(@NOTA_1 > 10)
			BEGIN
				PRINT('A PRIMEIRA NOTA DEVE ESTAR NO INTERVALO ENTRE 0 E 10')				
			END
		ELSE
			BEGIN
				UPDATE MATRICULA
				SET NOTA_1 = @NOTA_1
				WHERE RA_ALUNO = @RA_ALUNO
			END
			
		IF(@NOTA_2 > 10)
			BEGIN
				PRINT('A SEGUNDA NOTA DEVE ESTAR NO INTERVALO ENTRE 0 E 10')
			END
		ELSE
			BEGIN
				UPDATE MATRICULA
				SET NOTA_2 = @NOTA_2
				WHERE RA_ALUNO = @RA_ALUNO
			END
END