CREATE PROCEDURE VERIFICAR_MATERIAS_CURSADAS
	@SIGLA_DISCIPLINA VARCHAR(20),
AS
SET @SIGLA_DISCIPLINA = '%' + @SIGLA_DISCIPLINA + '%';

SELECT A.RA, A.NOME, D.SIGLA, D.NOME, M.NOTA_1, M.NOTA_2, M.SUBSTITUTIVA, M.MEDIA, M.FREQUENCIA, M.FALTA, M.STATUS
FROM MATRICULA M
INNER JOIN ALUNO A ON (M.RA_ALUNO = A.RA)
INNER JOIN DISCIPLINA D ON (M.SIGLA_DISCIPLINA = D.SIGLA)
WHERE ANO = '2021'
GO


CREATE PROCEDURE VERIFICAR_MATERIAS_CURSADAS_2021_2
	@RA_ALUNO VARCHAR(20)
AS
SELECT A.RA, A.NOME, D.SIGLA, D.NOME, M.NOTA_1, M.NOTA_2, M.SUBSTITUTIVA, M.MEDIA, M.FREQUENCIA, M.FALTA
FROM MATRICULA M
INNER JOIN ALUNO A ON (M.RA_ALUNO = A.RA)
INNER JOIN DISCIPLINA D ON (M.SIGLA_DISCIPLINA = D.SIGLA)
WHERE ANO = '2021' AND SEMESTRE = '2'
GO

CREATE PROCEDURE VERIFICAR_ALUNOS_REPROVADOS
AS
SELECT A.RA, A.NOME, D.SIGLA, D.NOME, M.NOTA_1, M.NOTA_2, M.SUBSTITUTIVA, M.MEDIA, M.FREQUENCIA, M.FALTA
FROM MATRICULA M
INNER JOIN ALUNO A ON (M.RA_ALUNO = A.RA)
INNER JOIN DISCIPLINA D ON (M.SIGLA_DISCIPLINA = D.SIGLA)
WHERE ANO = '2021' AND SEMESTRE = '2' AND M.STATUS LIKE '%REPROVADO%'
GO


CREATE PROCEDURE VERIFICAR_MATERIAS_CURSADAS_2021
AS
SELECT A.RA, A.NOME, D.SIGLA, D.NOME, M.NOTA_1, M.NOTA_2, M.SUBSTITUTIVA, M.MEDIA, M.FREQUENCIA, M.FALTA
FROM MATRICULA M
INNER JOIN ALUNO A ON (M.RA_ALUNO = A.RA)
INNER JOIN DISCIPLINA D ON (M.SIGLA_DISCIPLINA = D.SIGLA)
WHERE ANO = '2021'
GO

EXEC.VERIFICAR_MATERIAS_CURSADAS_2021

EXEC.VERIFICAR_MATERIAS_CURSADAS_2021_2 '0220481923002'

EXEC.VERIFICAR_ALUNOS_REPROVADOS