CREATE TABLE ALUNO(
	RA	VARCHAR(20) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	TELEFONE VARCHAR(12) NOT NULL,
	ENDERECO_LOCALIDADE VARCHAR(100) NOT NULL,
	ENDERECO_LOGRADOURO VARCHAR(100) NOT NULL,
	ENDERECO_NUMERO INT NOT NULL,
	ENDERECO_BAIRRO VARCHAR(100) NOT NULL,
	ENDERECO_UF VARCHAR(2) NOT NULL,
	ENDERECO_CEP VARCHAR(9) NOT NULL,
	ENDERECO_COMPLEMENTO VARCHAR(100) NULL,

)

CREATE TABLE DISCIPLINA (
	SIGLA VARCHAR(20) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CARGA_HORARIA INT NOT NULL
)

CREATE TABLE MATRICULA (
	NUMERO_MATRICULA INT IDENTITY(1,1) NOT NULL,
	ANO VARCHAR(4) NOT NULL,
	SEMESTRE VARCHAR(2) NOT NULL,
	RA_ALUNO VARCHAR(20) NOT NULL,
	SIGLA_DISCIPLINA VARCHAR(20) NOT NULL,
	NOTA_1 DECIMAL(4,2) NULL,
	NOTA_2 DECIMAL(4,2)  NULL,
	MEDIA DECIMAL(4,2) NULL,
	SUBSTITUTIVA DECIMAL(4,2) NULL,
	STATUS VARCHAR(20) NULL,
	FREQUENCIA INT NULL,
	FALTA INT NULL
)