
ALTER TABLE ALUNO
	ADD CONSTRAINT PK_ALUNO PRIMARY KEY CLUSTERED(RA) 

ALTER TABLE DISCIPLINA 
	ADD CONSTRAINT PK_DISCIPLINA PRIMARY KEY CLUSTERED(SIGLA)

ALTER TABLE MATRICULA 
	ADD CONSTRAINT PK_MATRICULA PRIMARY KEY CLUSTERED(NUMERO_MATRICULA, ANO, SEMESTRE, RA_ALUNO, SIGLA_DISCIPLINA) 

/*ALTER TABLE MATRICULA
	ADD CONSTRAINT PK_MATRICULA PRIMARY KEY CLUSTERED(ANO, SEMESTRE)
*/

ALTER TABLE MATRICULA
	ADD CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY(RA_ALUNO)
	REFERENCES ALUNO(RA)

ALTER TABLE MATRICULA
	ADD CONSTRAINT FK_MATRICULA_DISCIPLINA FOREIGN KEY(SIGLA_DISCIPLINA)
	REFERENCES DISCIPLINA(SIGLA)
