CREATE TRIGGER TG_VERIFICAR_SITUACAO_ALUNO_AI
ON MATRICULA
AFTER INSERT
AS
BEGIN
	DECLARE
		@NUMERO_MATRICULA INT,
		@NOTA_1 DECIMAL(4,2),
		@NOTA_2 DECIMAL(4,2),
		@MEDIA DECIMAL(4,2),
		@SUBSTITUTIVA DECIMAL(4,2),
		@CARGA_HORARIA INT,
		@FALTA INT,
		@FREQUENCIA INT,
		@SIGLA VARCHAR(20),
		@QUANTIDADE_FALTAS INT,
		@STATUS VARCHAR(20)

		SELECT @NUMERO_MATRICULA = NUMERO_MATRICULA, @NOTA_1 = NOTA_1, @NOTA_2 = NOTA_2, @SUBSTITUTIVA = SUBSTITUTIVA , @MEDIA = MEDIA, @FALTA = FALTA, @SIGLA = SIGLA_DISCIPLINA FROM INSERTED
		SELECT @CARGA_HORARIA = CARGA_HORARIA FROM DISCIPLINA
		WHERE SIGLA = @SIGLA
		SET @QUANTIDADE_FALTAS = CAST(@CARGA_HORARIA * 0.25 AS INT)
		PRINT('QUANTIDADE FALTAS')
		PRINT(@QUANTIDADE_FALTAS)
		PRINT('FALTAS')
		PRINT(@FALTA)

		SET @STATUS = ''

		IF(@NOTA_1 < @NOTA_2) AND (@SUBSTITUTIVA <> 0)
			BEGIN
				SET @MEDIA = ((@SUBSTITUTIVA + @NOTA_2) /2)
			END
		ELSE IF (@NOTA_2 < @NOTA_1) AND (@SUBSTITUTIVA <> 0)
			BEGIN
				SET @MEDIA = ((@NOTA_1 + @SUBSTITUTIVA) /2)
			END
		ELSE
			BEGIN
				SET @MEDIA = ((@NOTA_1 + @NOTA_2) /2)
			END

		IF(@FALTA > @QUANTIDADE_FALTAS)
			BEGIN
				SET @STATUS = 'REPROVADO POR FALTAS'
				PRINT(@STATUS)
			END
		ELSE IF (@FALTA <= @QUANTIDADE_FALTAS)
			BEGIN
				IF(@MEDIA < 5.0)
					BEGIN
						SET @STATUS = 'REPROVADO POR NOTA'
					END
				ELSE
					BEGIN
						SET @STATUS = 'APROVADO'
					END
			END


		PRINT(@STATUS)
		UPDATE MATRICULA
		SET STATUS = @STATUS, SUBSTITUTIVA = @SUBSTITUTIVA,  MEDIA = @MEDIA
		WHERE NUMERO_MATRICULA = @NUMERO_MATRICULA
END
GO